# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywebview.ui'
#
# Created: Tue Sep 25 02:44:58 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MyWebView(object):
    def setupUi(self, MyWebView):
        MyWebView.setObjectName(_fromUtf8("MyWebView"))
        MyWebView.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MyWebView)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkbox_preview = QtGui.QCheckBox(self.centralwidget)
        self.checkbox_preview.setObjectName(_fromUtf8("checkbox_preview"))
        self.horizontalLayout_2.addWidget(self.checkbox_preview)
        self.css_combobox = QtGui.QComboBox(self.centralwidget)
        self.css_combobox.setObjectName(_fromUtf8("css_combobox"))
        self.horizontalLayout_2.addWidget(self.css_combobox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editor_window = QtGui.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FixedSys"))
        font.setKerning(True)
        self.editor_window.setFont(font)
        self.editor_window.setObjectName(_fromUtf8("editor_window"))
        self.horizontalLayout.addWidget(self.editor_window)
        self.my_webview = QtWebKit.QWebView(self.centralwidget)
        self.my_webview.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.my_webview.setObjectName(_fromUtf8("my_webview"))
        self.horizontalLayout.addWidget(self.my_webview)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MyWebView.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MyWebView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.file_menu = QtGui.QMenu(self.menubar)
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.help_menu = QtGui.QMenu(self.menubar)
        self.help_menu.setObjectName(_fromUtf8("help_menu"))
        self.edit_menu = QtGui.QMenu(self.menubar)
        self.edit_menu.setObjectName(_fromUtf8("edit_menu"))
        self.ins_menu = QtGui.QMenu(self.menubar)
        self.ins_menu.setObjectName(_fromUtf8("ins_menu"))
        self.menu_ins_head = QtGui.QMenu(self.ins_menu)
        self.menu_ins_head.setObjectName(_fromUtf8("menu_ins_head"))
        self.view_menu = QtGui.QMenu(self.menubar)
        self.view_menu.setObjectName(_fromUtf8("view_menu"))
        MyWebView.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MyWebView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MyWebView.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MyWebView)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MyWebView.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_open = QtGui.QAction(MyWebView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save = QtGui.QAction(MyWebView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon1)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_saveas = QtGui.QAction(MyWebView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_saveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_saveas.setIcon(icon2)
        self.action_saveas.setObjectName(_fromUtf8("action_saveas"))
        self.action_exit = QtGui.QAction(MyWebView)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon3)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_help = QtGui.QAction(MyWebView)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_help.setIcon(icon4)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_sampleload = QtGui.QAction(MyWebView)
        self.action_sampleload.setObjectName(_fromUtf8("action_sampleload"))
        self.action_about = QtGui.QAction(MyWebView)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_copy = QtGui.QAction(MyWebView)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_copy.setIcon(icon5)
        self.action_copy.setObjectName(_fromUtf8("action_copy"))
        self.action_paste = QtGui.QAction(MyWebView)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paste.setIcon(icon6)
        self.action_paste.setObjectName(_fromUtf8("action_paste"))
        self.action_cut = QtGui.QAction(MyWebView)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cut.setIcon(icon7)
        self.action_cut.setObjectName(_fromUtf8("action_cut"))
        self.action_delete = QtGui.QAction(MyWebView)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_delete.setIcon(icon8)
        self.action_delete.setObjectName(_fromUtf8("action_delete"))
        self.action_duplicate = QtGui.QAction(MyWebView)
        self.action_duplicate.setObjectName(_fromUtf8("action_duplicate"))
        self.action_ins_head2 = QtGui.QAction(MyWebView)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_h2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_head2.setIcon(icon9)
        self.action_ins_head2.setObjectName(_fromUtf8("action_ins_head2"))
        self.action_ins_head3 = QtGui.QAction(MyWebView)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_h3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_head3.setIcon(icon10)
        self.action_ins_head3.setObjectName(_fromUtf8("action_ins_head3"))
        self.action_ins_head4 = QtGui.QAction(MyWebView)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_h4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_head4.setIcon(icon11)
        self.action_ins_head4.setObjectName(_fromUtf8("action_ins_head4"))
        self.action_ins_ul = QtGui.QAction(MyWebView)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_ul.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_ul.setIcon(icon12)
        self.action_ins_ul.setObjectName(_fromUtf8("action_ins_ul"))
        self.action_ins_ol = QtGui.QAction(MyWebView)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_ol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_ol.setIcon(icon13)
        self.action_ins_ol.setObjectName(_fromUtf8("action_ins_ol"))
        self.action_ins_hr = QtGui.QAction(MyWebView)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_hr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_hr.setIcon(icon14)
        self.action_ins_hr.setObjectName(_fromUtf8("action_ins_hr"))
        self.action_ins_link = QtGui.QAction(MyWebView)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_link.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_link.setIcon(icon15)
        self.action_ins_link.setObjectName(_fromUtf8("action_ins_link"))
        self.action_ins_image = QtGui.QAction(MyWebView)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_img.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_image.setIcon(icon16)
        self.action_ins_image.setObjectName(_fromUtf8("action_ins_image"))
        self.action_ins_cite = QtGui.QAction(MyWebView)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_cite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_cite.setIcon(icon17)
        self.action_ins_cite.setObjectName(_fromUtf8("action_ins_cite"))
        self.action_ins_code_word = QtGui.QAction(MyWebView)
        self.action_ins_code_word.setObjectName(_fromUtf8("action_ins_code_word"))
        self.action_config = QtGui.QAction(MyWebView)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_config.setIcon(icon18)
        self.action_config.setObjectName(_fromUtf8("action_config"))
        self.action_html_reload = QtGui.QAction(MyWebView)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_html_reload.setIcon(icon19)
        self.action_html_reload.setObjectName(_fromUtf8("action_html_reload"))
        self.action_ins_br = QtGui.QAction(MyWebView)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_newline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_br.setIcon(icon20)
        self.action_ins_br.setObjectName(_fromUtf8("action_ins_br"))
        self.action_ins_idlink = QtGui.QAction(MyWebView)
        self.action_ins_idlink.setObjectName(_fromUtf8("action_ins_idlink"))
        self.action_ins_em = QtGui.QAction(MyWebView)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_em.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_em.setIcon(icon21)
        self.action_ins_em.setObjectName(_fromUtf8("action_ins_em"))
        self.action_ins_strong = QtGui.QAction(MyWebView)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_strong.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_strong.setIcon(icon22)
        self.action_ins_strong.setObjectName(_fromUtf8("action_ins_strong"))
        self.action_ins_code_multi = QtGui.QAction(MyWebView)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_pre.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_code_multi.setIcon(icon23)
        self.action_ins_code_multi.setObjectName(_fromUtf8("action_ins_code_multi"))
        self.action_preview_set = QtGui.QAction(MyWebView)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_preview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_preview_set.setIcon(icon24)
        self.action_preview_set.setObjectName(_fromUtf8("action_preview_set"))
        self.action_export_html = QtGui.QAction(MyWebView)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_export_html.setIcon(icon25)
        self.action_export_html.setObjectName(_fromUtf8("action_export_html"))
        self.action_ins_head6 = QtGui.QAction(MyWebView)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_h6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_head6.setIcon(icon26)
        self.action_ins_head6.setObjectName(_fromUtf8("action_ins_head6"))
        self.action_ins_head1 = QtGui.QAction(MyWebView)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_h1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_head1.setIcon(icon27)
        self.action_ins_head1.setObjectName(_fromUtf8("action_ins_head1"))
        self.action_ins_head5 = QtGui.QAction(MyWebView)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/icon_24x24_h5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ins_head5.setIcon(icon28)
        self.action_ins_head5.setObjectName(_fromUtf8("action_ins_head5"))
        self.action_font = QtGui.QAction(MyWebView)
        self.action_font.setObjectName(_fromUtf8("action_font"))
        self.file_menu.addAction(self.action_open)
        self.file_menu.addAction(self.action_save)
        self.file_menu.addAction(self.action_saveas)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.action_export_html)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.action_exit)
        self.help_menu.addAction(self.action_help)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.action_about)
        self.edit_menu.addAction(self.action_copy)
        self.edit_menu.addAction(self.action_paste)
        self.edit_menu.addAction(self.action_cut)
        self.edit_menu.addAction(self.action_delete)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.action_duplicate)
        self.menu_ins_head.addAction(self.action_ins_head1)
        self.menu_ins_head.addAction(self.action_ins_head2)
        self.menu_ins_head.addAction(self.action_ins_head3)
        self.menu_ins_head.addAction(self.action_ins_head4)
        self.menu_ins_head.addAction(self.action_ins_head5)
        self.menu_ins_head.addAction(self.action_ins_head6)
        self.ins_menu.addAction(self.menu_ins_head.menuAction())
        self.ins_menu.addAction(self.action_ins_ul)
        self.ins_menu.addAction(self.action_ins_ol)
        self.ins_menu.addAction(self.action_ins_hr)
        self.ins_menu.addAction(self.action_ins_link)
        self.ins_menu.addAction(self.action_ins_idlink)
        self.ins_menu.addAction(self.action_ins_image)
        self.ins_menu.addAction(self.action_ins_cite)
        self.ins_menu.addAction(self.action_ins_code_multi)
        self.ins_menu.addAction(self.action_ins_code_word)
        self.ins_menu.addAction(self.action_ins_br)
        self.ins_menu.addAction(self.action_ins_strong)
        self.ins_menu.addAction(self.action_ins_em)
        self.view_menu.addAction(self.action_html_reload)
        self.view_menu.addAction(self.action_preview_set)
        self.view_menu.addAction(self.action_font)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.ins_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addAction(self.action_saveas)
        self.toolBar.addAction(self.action_export_html)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_ins_head1)
        self.toolBar.addAction(self.action_ins_head2)
        self.toolBar.addAction(self.action_ins_head3)
        self.toolBar.addAction(self.action_ins_ul)
        self.toolBar.addAction(self.action_ins_ol)
        self.toolBar.addAction(self.action_ins_link)
        self.toolBar.addAction(self.action_ins_image)
        self.toolBar.addAction(self.action_ins_code_multi)
        self.toolBar.addAction(self.action_ins_cite)
        self.toolBar.addAction(self.action_ins_hr)
        self.toolBar.addAction(self.action_ins_br)
        self.toolBar.addAction(self.action_ins_strong)
        self.toolBar.addAction(self.action_ins_em)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_html_reload)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_help)
        self.toolBar.addAction(self.action_exit)

        self.retranslateUi(MyWebView)
        QtCore.QMetaObject.connectSlotsByName(MyWebView)

    def retranslateUi(self, MyWebView):
        MyWebView.setWindowTitle(QtGui.QApplication.translate("MyWebView", "MarkDownEditPyQt", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_preview.setText(QtGui.QApplication.translate("MyWebView", "リアルタイムプレビュー", None, QtGui.QApplication.UnicodeUTF8))
        self.file_menu.setTitle(QtGui.QApplication.translate("MyWebView", "ファイル(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.help_menu.setTitle(QtGui.QApplication.translate("MyWebView", "ヘルプ(&H)", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_menu.setTitle(QtGui.QApplication.translate("MyWebView", "編集(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.ins_menu.setTitle(QtGui.QApplication.translate("MyWebView", "挿入(&I)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_ins_head.setTitle(QtGui.QApplication.translate("MyWebView", "見出し (&H)", None, QtGui.QApplication.UnicodeUTF8))
        self.view_menu.setTitle(QtGui.QApplication.translate("MyWebView", "表示(&V)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MyWebView", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MyWebView", "開く(&O)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setToolTip(QtGui.QApplication.translate("MyWebView", "mdファイルを開く", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MyWebView", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setText(QtGui.QApplication.translate("MyWebView", "保存(&S)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setToolTip(QtGui.QApplication.translate("MyWebView", "mdファイルを保存", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setShortcut(QtGui.QApplication.translate("MyWebView", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveas.setText(QtGui.QApplication.translate("MyWebView", "別名保存", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveas.setToolTip(QtGui.QApplication.translate("MyWebView", "別名で保存", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveas.setShortcut(QtGui.QApplication.translate("MyWebView", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MyWebView", "終了(&X)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setShortcut(QtGui.QApplication.translate("MyWebView", "Alt+X", None, QtGui.QApplication.UnicodeUTF8))
        self.action_help.setText(QtGui.QApplication.translate("MyWebView", "ヘルプ", None, QtGui.QApplication.UnicodeUTF8))
        self.action_sampleload.setText(QtGui.QApplication.translate("MyWebView", "サンプル表示", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("MyWebView", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setText(QtGui.QApplication.translate("MyWebView", "コピー(&C)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setShortcut(QtGui.QApplication.translate("MyWebView", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_paste.setText(QtGui.QApplication.translate("MyWebView", "貼り付け(&V)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_paste.setShortcut(QtGui.QApplication.translate("MyWebView", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.action_cut.setText(QtGui.QApplication.translate("MyWebView", "切り取り(&X)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_cut.setShortcut(QtGui.QApplication.translate("MyWebView", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete.setText(QtGui.QApplication.translate("MyWebView", "削除", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete.setShortcut(QtGui.QApplication.translate("MyWebView", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.action_duplicate.setText(QtGui.QApplication.translate("MyWebView", "行を複製(&D)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_duplicate.setShortcut(QtGui.QApplication.translate("MyWebView", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_head2.setText(QtGui.QApplication.translate("MyWebView", "見出し2 (&2)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_head3.setText(QtGui.QApplication.translate("MyWebView", "見出し3 (&3)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_head4.setText(QtGui.QApplication.translate("MyWebView", "見出し4 (&4)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_ul.setText(QtGui.QApplication.translate("MyWebView", "番号無しリスト (&U)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_ol.setText(QtGui.QApplication.translate("MyWebView", "番号付きリスト (&O)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_hr.setText(QtGui.QApplication.translate("MyWebView", "水平線 (&R)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_link.setText(QtGui.QApplication.translate("MyWebView", "リンク (&L)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_image.setText(QtGui.QApplication.translate("MyWebView", "画像 (&I)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_cite.setText(QtGui.QApplication.translate("MyWebView", "引用", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_code_word.setText(QtGui.QApplication.translate("MyWebView", "コード断片", None, QtGui.QApplication.UnicodeUTF8))
        self.action_config.setText(QtGui.QApplication.translate("MyWebView", "設定", None, QtGui.QApplication.UnicodeUTF8))
        self.action_html_reload.setText(QtGui.QApplication.translate("MyWebView", "html表示を更新", None, QtGui.QApplication.UnicodeUTF8))
        self.action_html_reload.setShortcut(QtGui.QApplication.translate("MyWebView", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_br.setText(QtGui.QApplication.translate("MyWebView", "改行", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_idlink.setText(QtGui.QApplication.translate("MyWebView", "参照リンク", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_em.setText(QtGui.QApplication.translate("MyWebView", "斜体", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_strong.setText(QtGui.QApplication.translate("MyWebView", "太字", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_code_multi.setText(QtGui.QApplication.translate("MyWebView", "コード複数行", None, QtGui.QApplication.UnicodeUTF8))
        self.action_preview_set.setText(QtGui.QApplication.translate("MyWebView", "リアルタイムプレビュー切替", None, QtGui.QApplication.UnicodeUTF8))
        self.action_export_html.setText(QtGui.QApplication.translate("MyWebView", "htmlエクスポート", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_head6.setText(QtGui.QApplication.translate("MyWebView", "見出し6 (&6)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_head1.setText(QtGui.QApplication.translate("MyWebView", "見出し1 (&1)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ins_head5.setText(QtGui.QApplication.translate("MyWebView", "見出し5 (&5)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_font.setText(QtGui.QApplication.translate("MyWebView", "フォント変更", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import resources_rc
